AND       and         aNd
BEGIN     begin       bEgIn
DIV       div         dIv
DO        do          Do
DOWNTO    downto      DownTo
ELSE      else        ELSe
END       end         ENd
FOR       for         foR
FUNCTION  function    fUnCtIoN
IF        if          If
MOD       mod         mOd
NOT       not         nOt
OR        or          oR
PROCEDURE procedure   proceDURE
PROGRAM   program     PROGram
READ      read        rEAD
REPEAT    repeat      RePeAT
THEN      then        TheN
TO        to          tO
UNTIL     until       untiL
VAR       var         vAr
WHILE     while       whiLE
WRITE     write       wRITe


a__
a
a_b___3
b_____5
_x3Z_5
_X3Z_5_

begins
ends
a3+b4-c/67
