

Tests/ir_test.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
ADD SP #1 SP
ADD SP #1 SP
ADD SP #1 SP
PUSH #1.2
CASTSF
CASTSF
POP 0(D0)
PUSH #2.4
CASTSF
PUSH 2(D0)
CASTSF
CASTSF
MULSF
CASTSF
POP 1(D0)
PUSH #5
CASTSF
CASTSF
POP 1(D0)
PUSH #1
CASTSI
PUSH 1(D0)
CASTSI
MULS
CASTSI
POP 2(D0)
MOV D0 SP
HLT

Tests/ir_test2.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
ADD SP #1 SP
ADD SP #1 SP
PUSH #1
CASTSI
PUSH #5
CASTSI
ADDS
CASTSI
POP 0(D0)
PUSH #2
CASTSI
PUSH 0(D0)
CASTSI
MULS
CASTSI
POP 1(D0)
RD 1(D0)
RD 0(D0)
PUSH 0(D0)
CASTSI
WRTS
PUSH #5
CASTSI
PUSH #6
CASTSI
ADDS
WRTS
PUSH 0(D0)
CASTSI
PUSH #0
CASTSI
CMPGTS
BRFS L1
BR L2
L1:
L2:
MOV D0 SP
HLT

Tests/ir_test3.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
ADD SP #1 SP
ADD SP #1 SP
ADD SP #1 SP
PUSH #1.5
CASTSI
CASTSI
POP 0(D0)
MOV D0 SP
HLT

Tests/ir_test4.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
ADD SP #1 SP
RD 0(D0)
PUSH 0(D0)
CASTSI
PUSH #0
CASTSI
CMPGTS
BRFS L1
PUSH 0(D0)
CASTSI
PUSH #5
CASTSI
MULS
CASTSI
POP 0(D0)
PUSH 0(D0)
CASTSI
WRTS
BR L2
L1:
PUSH 0(D0)
CASTSI
PUSH #7
CASTSI
MULS
CASTSI
POP 0(D0)
PUSH 0(D0)
CASTSI
WRTS
L2:
MOV D0 SP
HLT

Tests/ir_test5.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
ADD SP #1 SP
PUSH #2
CASTSI
CASTSI
POP 0(D0)
L1:
PUSH 0(D0)
CASTSI
PUSH #20
CASTSI
CMPLTS
BRFS L2
PUSH 0(D0)
CASTSI
PUSH #5
CASTSI
MULS
CASTSI
POP 0(D0)
PUSH 0(D0)
CASTSI
WRTS
BR L1
L2:
MOV D0 SP
HLT

Tests/ir_test6.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
ADD SP #1 SP
PUSH #2
CASTSI
CASTSI
POP 0(D0)
L1:
PUSH 0(D0)
CASTSI
PUSH #5
CASTSI
MULS
CASTSI
POP 0(D0)
PUSH 0(D0)
CASTSI
WRTS
PUSH 0(D0)
CASTSI
PUSH #20
CASTSI
CMPLTS
BRFS L1
MOV D0 SP
HLT

Tests/ir_test_For.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
ADD SP #1 SP
ADD SP #1 SP
PUSH #2
CASTSI
CASTSI
POP 0(D0)
L1:
PUSH 0(D0)
CASTSI
PUSH #4
CASTSI
CMPEQS
BRTS L2
PUSH 0(D0)
CASTSI
WRTS
ADD 0(D0) #1 0(D0)
BR L1
L2:
MOV D0 SP
HLT

Tests/parse_test.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
ADD SP #1 SP
MOV D0 SP
HLT

Tests/parse_test2.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
ADD SP #1 SP
ADD SP #1 SP
ADD SP #1 SP
MOV SP D1
ADD SP #1 SP
ADD SP #1 SP
PUSH #1
CASTSI
CASTSI
POP 2(D1)
PUSH #0
CASTSI
CASTSI
POP 1(D1)
L1:
PUSH 2(D1)
CASTSI
PUSH 0(D1)
CASTSI
CMPLES
BRFS L2
PUSH 1(D1)
CASTSI
PUSH 2(D1)
CASTSI
ADDS
CASTSI
POP 1(D1)
PUSH 2(D1)
CASTSI
PUSH #1
CASTSI
ADDS
CASTSI
POP 2(D1)
BR L1
L2:
MOV D1 SP

Tests/parse_test_bug.mp

Tests/parse_test_failure.mp
Failed at column 32, line 4 with message: Expected MP_EOF but found MP_IDENTIFIER

Tests/TestsFromPersons/tests/casting_test.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
ADD SP #1 SP
ADD SP #1 SP
PUSH #2.5
CASTSI
CASTSI
POP 0(D0)
PUSH #3.5
CASTSF
CASTSF
POP 1(D0)
PUSH #"This should output 8.5"
WRTLNS
PUSH 0(D0)
CASTSF
PUSH 1(D0)
CASTSF
CASTSF
ADDSF
WRTLNS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/casting_test2.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
ADD SP #1 SP
ADD SP #1 SP
PUSH #4
CASTSI
CASTSI
POP 0(D0)
PUSH #4.1
CASTSF
CASTSF
POP 1(D0)
PUSH #"This should return True"
WRTLNS
PUSH 1(D0)
CASTSF
PUSH 0(D0)
CASTSF
CMPGTSF
WRTLNS
PUSH #"This should return False"
WRTLNS
PUSH 0(D0)
CASTSF
PUSH 1(D0)
CASTSF
CMPGTSF
WRTLNS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/casting_test_bool_fail.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
PUSH #"This next line should fail"
WRTLNS
PUSH #1
PUSH #0
CMPGTS
WRTS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/casting_test_equalBools.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
ADD SP #1 SP
PUSH #1
CASTSI
POP 0(D0)
PUSH #"Prgram casting_test_equalsBool"
WRTLNS
PUSH #"This next line should return True"
WRTLNS
PUSH 0(D0)
PUSH #1
CMPEQS
WRTLNS
PUSH #"This next line should return False"
WRTLNS
PUSH 0(D0)
PUSH #0
CMPEQS
WRTLNS
PUSH #"This next line should return False"
WRTLNS
PUSH #0
PUSH #0
CMPNES
WRTS
PUSH #"This next line should return True"
WRTLNS
PUSH 0(D0)
PUSH #0
CMPNES
WRTLNS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/casting_test_equals.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
ADD SP #1 SP
ADD SP #1 SP
ADD SP #1 SP
ADD SP #1 SP
PUSH #7.15
CASTSF
CASTSF
POP 0(D0)
PUSH #88.88
CASTSF
CASTSF
POP 1(D0)
PUSH #505
CASTSI
CASTSI
POP 2(D0)
PUSH #1
CASTSI
CASTSI
POP 3(D0)
PUSH #"Program casting_test_equals"
WRTLNS
PUSH #"Output should be False"
WRTLNS
PUSH 0(D0)
CASTSF
PUSH 2(D0)
CASTSF
CMPEQSF
WRTLNS
PUSH #"Output should be False"
WRTLNS
PUSH 3(D0)
CASTSF
PUSH 0(D0)
CASTSF
CMPEQSF
WRTLNS
PUSH #"Output should be True"
WRTLNS
PUSH 2(D0)
CASTSF
PUSH #505.00
CASTSF
CMPEQSF
WRTLNS
PUSH #"Output should be True"
WRTLNS
PUSH 0(D0)
CASTSF
PUSH #7.150
CASTSF
CMPEQSF
WRTLNS
PUSH #"Output should be False"
WRTLNS
PUSH 3(D0)
CASTSF
PUSH #2
CASTSF
CMPEQSF
WRTLNS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/casting_test_equals_fail.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
PUSH #"Next line should break"
WRTLNS
PUSH #"This String"
PUSH #"That String"
CMPEQS
WRTLNS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/casting_test_greaterEqual_fail.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
ADD SP #1 SP
ADD SP #1 SP
PUSH #"Mudkipz"
POP 0(D0)
PUSH #"I heard u leik em"
POP 1(D0)
PUSH #"This next line should fail"
WRTLNS
PUSH 0(D0)
PUSH 1(D0)
CMPLES
WRTLNS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/casting_test_greater_fail.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
ADD SP #1 SP
ADD SP #1 SP
PUSH #"Just us sleeping chickens"
POP 0(D0)
PUSH #5
CASTSI
CASTSI
POP 1(D0)
PUSH #"This code should fail"
WRTLNS
PUSH 0(D0)
PUSH 1(D0)
CASTSI
CMPGTS
WRTLNS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/casting_test_less.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
ADD SP #1 SP
ADD SP #1 SP
ADD SP #1 SP
ADD SP #1 SP
PUSH #3.14
CASTSF
CASTSF
POP 0(D0)
PUSH #5.5
CASTSF
CASTSF
POP 2(D0)
PUSH #13
CASTSI
CASTSI
POP 1(D0)
PUSH #7
CASTSI
CASTSI
POP 3(D0)
PUSH #"Program casting_test_less"
WRTLNS
PUSH #"Output should be False for 3.14 < -5.5"
WRTLNS
PUSH 0(D0)
CASTSF
PUSH 2(D0)
CASTSF
CMPLTSF
WRTLNS
PUSH #"Output should be True"
WRTLNS
PUSH 0(D0)
CASTSF
PUSH 1(D0)
CASTSF
CMPLTSF
WRTLNS
PUSH #"Output should be False"
WRTLNS
PUSH 3(D0)
CASTSF
PUSH 2(D0)
CASTSF
CMPLTSF
WRTLNS
PUSH #"Ouput should be True"
WRTLNS
PUSH 3(D0)
CASTSF
PUSH 1(D0)
CASTSF
CMPLTSF
WRTLNS
PUSH #"Output should be False for hardcoded float < int"
WRTLNS
PUSH #105.501
CASTSF
PUSH #100
CASTSF
CMPLTSF
WRTLNS
PUSH #"Output should be True for hardcoded int < float"
WRTLNS
PUSH #50
CASTSF
PUSH #50.001
CASTSF
CMPLTSF
WRTLNS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/casting_test_lessEqual.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
ADD SP #1 SP
ADD SP #1 SP
PUSH #500
CASTSI
CASTSI
POP 0(D0)
PUSH #500.50
CASTSF
CASTSF
POP 1(D0)
PUSH #"Program casting_test_less_equal"
WRTLNS
PUSH #"Output should be False"
WRTLNS
PUSH 1(D0)
CASTSF
PUSH 0(D0)
CASTSF
CMPLESF
WRTLNS
PUSH #"Output should be True"
WRTLNS
PUSH 0(D0)
CASTSF
PUSH 1(D0)
CASTSF
CMPLESF
WRTLNS
PUSH #"Output should be False"
WRTLNS
PUSH 1(D0)
CASTSF
PUSH #500.40
CASTSF
CMPLESF
WRTLNS
PUSH #"Output should be True"
WRTLNS
PUSH 1(D0)
CASTSF
PUSH #500.50
CASTSF
CMPLESF
WRTLNS
PUSH #"Output should be True"
WRTLNS
PUSH 0(D0)
CASTSF
PUSH #500
CASTSF
CMPLESF
WRTLNS
PUSH #"Testing to see if this is greater than or equal for 5 >= 6"
WRTLNS
PUSH #5
CASTSF
PUSH #6
CASTSF
CMPGESF
WRTLNS
PUSH #"Testing to see if this is less than or equal for 5 <= 6"
WRTLNS
PUSH #5
CASTSF
PUSH #6
CASTSF
CMPLESF
WRTLNS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/casting_test_lessEqual_fail.mp
Failed at column 14, line 3 with message: Expected MP_EOF but found MP_FIXED_LIT

Tests/TestsFromPersons/tests/casting_test_less_fail.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
ADD SP #1 SP
ADD SP #1 SP
PUSH #1
CASTSI
POP 0(D0)
PUSH #7
CASTSI
CASTSI
POP 1(D0)
PUSH #"This following code should fail"
WRTLNS
PUSH 0(D0)
PUSH 1(D0)
CASTSI
CMPGTS
WRTLNS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/casting_test_notEqual.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
ADD SP #1 SP
ADD SP #1 SP
PUSH #65.666
CASTSF
CASTSF
POP 0(D0)
PUSH #50
CASTSI
CASTSI
POP 1(D0)
PUSH #"This next line should return True"
WRTLNS
PUSH 0(D0)
CASTSF
PUSH 1(D0)
CASTSF
CMPNESF
WRTLNS
PUSH #"This next line should return False"
WRTLNS
PUSH 0(D0)
CASTSF
PUSH #65.666
CASTSF
CMPNESF
WRTLNS
PUSH #"This next line should return True"
WRTLNS
PUSH 1(D0)
CASTSF
PUSH #50.05
CASTSF
CMPNESF
WRTLNS
PUSH #"This next line should return False"
WRTLNS
PUSH 1(D0)
CASTSF
PUSH #50
CASTSF
CMPNESF
WRTLNS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/casting_test_notEqualBool.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
PUSH #"Next line should be False"
WRTLNS
PUSH #1
PUSH #1
CMPNES
WRTS
PUSH #"Next line should be True"
WRTLNS
PUSH #1
PUSH #0
CMPNES
WRTS
PUSH #"Next line should be True"
WRTLNS
PUSH #1
PUSH #0
CMPNES
PUSH #0
CMPNES
WRTS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/expression_add_test.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
PUSH #3
CASTSI
PUSH #4
CASTSI
ADDS
PUSH #5
CASTSI
ADDS
WRTS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/expression_add_test_10.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
PUSH #50
CASTSF
PUSH #60.60
CASTSF
ORS
WRTLNS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/expression_add_test_11.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
PUSH #FALSE
CASTSF
PUSH #13.5
CASTSF
ORS
WRTS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/expression_add_test_2.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
PUSH #2
CASTSI
PUSH #3
CASTSI
ADDS
WRTLNS
PUSH #1.2
CASTSF
PUSH #5
CASTSF
CASTSF
ADDSF
WRTS
PUSH #2
CASTSF
PUSH #5.7
CASTSF
CASTSF
ADDSF
WRTS
PUSH #2.3
CASTSF
PUSH #77.3
CASTSF
CASTSF
ADDSF
WRTS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/expression_add_test_3.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
PUSH #1
CASTSI
PUSH #6
CASTSI
SUBS
WRTLNS
PUSH #7.5
CASTSF
PUSH #2
CASTSF
CASTSF
SUBSF
WRTLNS
PUSH #8
CASTSF
PUSH #1256
CASTSF
CASTSF
SUBSF
WRTLNS
PUSH #551.72
CASTSF
PUSH #0.0002
CASTSF
CASTSF
SUBSF
WRTS
PUSH #1.0e2
CASTSF
PUSH #2.0E-1
CASTSF
CASTSF
SUBSF
WRTS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/expression_add_test_4.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
PUSH #"mahesh output start"
WRTLNS
PUSH #1
PUSH #1
ORS
WRTS
PUSH #0
PUSH #1
ORS
WRTS
PUSH #1
PUSH #0
ORS
WRTS
PUSH #0
PUSH #0
ORS
WRTS
PUSH #"mahesh output end"
WRTLNS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/expression_add_test_5.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
PUSH #"MyString"
PUSH #2
CASTSI
ADDS
WRTLNS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/expression_add_test_6.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
PUSH #0
PUSH #2
CASTSI
ADDS
WRTS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/expression_add_test_7.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
PUSH #"MyString"
PUSH #0
CASTSI
SUBS
WRTLNS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/expression_add_test_8.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
PUSH #1
PUSH #9156
CASTSI
SUBS
WRTS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/expression_add_test_9.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
PUSH #"FirstString"
PUSH #"SecondString"
ORS
WRTLNS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/expression_and_4test.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
PUSH #"Program: Expression_and_4test"
WRTLNS
PUSH #"Should output 0"
WRTLNS
PUSH #1
PUSH #0
ANDS
WRTS
PUSH #"Should output 0"
WRTLNS
PUSH #0
PUSH #1
ANDS
WRTS
PUSH #"should output 1"
WRTLNS
PUSH #1
PUSH #1
ANDS
WRTS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/expression_div_4test.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
PUSH #"Should print out 50"
WRTLNS
PUSH #100
CASTSI
PUSH #2
CASTSI
DIVS
WRTLNS
PUSH #"Next output should be 7"
WRTLNS
PUSH #21
CASTSF
PUSH #3.0
CASTSF
CASTSF
DIVSF
WRTLNS
PUSH #"Next output should be 2"
WRTLNS
PUSH #5.0
CASTSF
PUSH #2
CASTSF
CASTSF
DIVSF
WRTLNS
PUSH #"Next output should be 2"
WRTLNS
PUSH #8.2
CASTSF
PUSH #4.1
CASTSF
CASTSF
DIVSF
WRTLNS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/expression_divf_4test.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
PUSH #"Program: Expression_div_4test"
WRTLNS
PUSH #"Should print out 50.0"
WRTLNS
PUSH #100
CASTSI
PUSH #2
CASTSI
CASTSF
DIVSF
WRTLNS
PUSH #"Next output should be 7"
WRTLNS
PUSH #21
CASTSF
PUSH #3.0
CASTSF
CASTSF
DIVSF
WRTLNS
PUSH #"Next output should be 2.5"
WRTLNS
PUSH #5.0
CASTSF
PUSH #2
CASTSF
CASTSF
DIVSF
WRTLNS
PUSH #"Next output should be 2.0"
WRTLNS
PUSH #8.2
CASTSF
PUSH #4.1
CASTSF
CASTSF
DIVSF
WRTLNS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/expression_mod_test.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
PUSH #"Expression_mod_test"
WRTLNS
PUSH #"expected result: 1"
WRTLNS
PUSH #7
CASTSI
PUSH #3
CASTSI
MODS
WRTLNS
PUSH #"expected result: 0"
WRTLNS
PUSH #12
CASTSI
PUSH #3
CASTSI
MODS
WRTLNS
PUSH #"probably will output 0"
WRTLNS
PUSH #30.1
CASTSF
PUSH #10
CASTSF
ERROR
WRTLNS
PUSH #"probably will output 2"
WRTLNS
PUSH #26
CASTSF
PUSH #6.9
CASTSF
ERROR
WRTLNS
PUSH #"expected result: 1"
WRTLNS
PUSH #7.3
CASTSF
PUSH #3.8
CASTSF
ERROR
WRTLNS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/expression_mul_4test.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
PUSH #"Expression_mul_4test"
WRTLNS
PUSH #"Should print out 200"
WRTLNS
PUSH #100
CASTSI
PUSH #2
CASTSI
MULS
WRTLNS
PUSH #"Next output should be 12.4"
WRTLNS
PUSH #4
CASTSF
PUSH #3.1
CASTSF
CASTSF
MULSF
WRTLNS
PUSH #"Next output should be 10.0"
WRTLNS
PUSH #5.0
CASTSF
PUSH #2
CASTSF
CASTSF
MULSF
WRTLNS
PUSH #"Next output should be 33.62"
WRTLNS
PUSH #8.2
CASTSF
PUSH #4.1
CASTSF
CASTSF
MULSF
WRTLNS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/expression_not_test.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
PUSH #"Not TRUE is: "
WRTS
PUSH #1
WRTS
PUSH #"Not FALSE is: "
WRTS
PUSH #0
WRTS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/expression_test.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
PUSH #8
CASTSI
PUSH #4
CASTSI
ADDS
PUSH #3
CASTSI
DIVS
WRTS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/for_loop.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
ADD SP #1 SP
PUSH #"Program: For_Loop"
WRTLNS
PUSH #"1,2,3, Rock & the loop is working right"
WRTLNS
PUSH #1
CASTSI
CASTSI
POP 0(D0)
L1:
PUSH 0(D0)
CASTSI
PUSH #4
CASTSI
CMPEQS
BRTS L2
PUSH 0(D0)
CASTSI
WRTS
PUSH #" O-Clock"
WRTLNS
ADD 0(D0) #1 0(D0)
BR L1
L2:
PUSH #"ROCK!"
WRTLNS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/hello_world.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
ADD SP #1 SP
PUSH #"HELLO WORLD!"
POP 0(D0)
PUSH 0(D0)
WRTLNS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/nasty_type_test.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
ADD SP #1 SP
ADD SP #1 SP
ADD SP #1 SP
PUSH #1
CASTSI
CASTSI
POP 0(D0)
PUSH #1
CASTSI
POP 1(D0)
PUSH #3.14
CASTSF
CASTSF
POP 2(D0)
PUSH #"myInt value is: "
WRTS
PUSH 0(D0)
CASTSI
WRTLNS
PUSH #"myBool is True"
WRTLNS
PUSH #"myFloat is: "
WRTS
PUSH 2(D0)
CASTSF
WRTLNS
PUSH #"Evaluting ((((( myInt * 5) * myFloat) / 2.2) >=  ((((2 + 2) div 4) * 2.25) - 1.45)) = myBool) Which should be True when all is done"
WRTLNS
PUSH 0(D0)
CASTSF
PUSH #5
CASTSF
CASTSF
MULSF
PUSH 2(D0)
CASTSF
CASTSF
MULSF
PUSH #2.2
CASTSF
CASTSF
DIVSF
PUSH #2
CASTSF
PUSH #2
CASTSF
CASTSF
ADDSF
PUSH #4
CASTSF
CASTSF
DIVSF
PUSH #2.25
CASTSF
CASTSF
MULSF
PUSH #1.45
CASTSF
CASTSF
SUBSF
CMPGESF
PUSH 1(D0)
CMPEQS
WRTS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/repeat_until.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
ADD SP #1 SP
PUSH #"Program: repeat_UNTIL"
WRTLNS
PUSH #"If loop is right, you should see BONGO! 3 times"
WRTLNS
PUSH #3
CASTSI
CASTSI
POP 0(D0)
L1:
PUSH #"BONGO!"
WRTLNS
PUSH 0(D0)
CASTSI
PUSH #1
CASTSI
SUBS
CASTSI
POP 0(D0)
PUSH 0(D0)
CASTSI
PUSH #1
CASTSI
CMPLTS
BRFS L1
PUSH #"Done with REPEAT"
WRTLNS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/simple_proc.mp

Tests/TestsFromPersons/tests/test_if_compound.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
ADD SP #1 SP
ADD SP #1 SP
ADD SP #1 SP
ADD SP #1 SP
PUSH #0
CASTSI
CASTSI
POP 0(D0)
PUSH #5
CASTSI
CASTSI
POP 1(D0)
PUSH #4
CASTSI
PUSH #5
CASTSI
MULS
PUSH #100
CASTSI
PUSH #19
CASTSI
MODS
CMPGES
PUSH #3
CASTSI
PUSH #3
CASTSI
ADDS
PUSH #3
CASTSI
PUSH #3
CASTSI
MULS
ADDS
PUSH #12
CASTSI
PUSH #45
CASTSI
MULS
PUSH #2
CASTSI
CASTSF
DIVSF
CMPLTS
ANDS
BRFS L1
PUSH #"All up in the then portion"
WRTLNS
PUSH #1
CASTSI
PUSH #5
CASTSI
MULS
PUSH #5
CASTSI
DIVS
CASTSI
POP 0(D0)
L3:
PUSH 0(D0)
CASTSI
PUSH 1(D0)
CASTSI
CMPEQS
BRTS L4
PUSH 0(D0)
CASTSI
WRTLNS
ADD 0(D0) #1 0(D0)
BR L3
L4:
PUSH #"Outa my for loops"
WRTLNS
PUSH #"I started another statement!"
WRTLNS
BR L2
L1:
PUSH #"How did we get here?"
WRTLNS
L2:
PUSH #"All done with the program!"
WRTLNS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/test_if_else.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
ADD SP #1 SP
PUSH #2
CASTSI
CASTSI
POP 0(D0)
PUSH 0(D0)
CASTSI
PUSH #3
CASTSI
CMPGTS
BRFS L1
PUSH #"A is greater than 3"
WRTLNS
BR L2
L1:
PUSH #"A is not greater than 3"
WRTLNS
L2:
PUSH #"Done with if"
WRTLNS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/test_if_else_compound.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
ADD SP #1 SP
PUSH #10
CASTSI
CASTSI
POP 0(D0)
PUSH 0(D0)
CASTSI
PUSH #0
CASTSI
CMPEQS
BRFS L1
PUSH #"I am in IF"
WRTLNS
BR L2
L1:
PUSH 0(D0)
CASTSI
PUSH #5
CASTSI
PUSH #3
CASTSI
MULS
PUSH #3
CASTSI
SUBS
PUSH #2
CASTSI
MULS
PUSH #14
CASTSI
SUBS
CMPEQS
BRFS L3
PUSH #"I am in ELSE. Compound statement in ELSE works."
WRTLNS
BR L4
L3:
L4:
L2:
PUSH #"I am out of the IF-ELSE."
WRTLNS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/test_if_inner_if_else.mp

Tests/TestsFromPersons/tests/test_simple_if.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
ADD SP #1 SP
PUSH #4
CASTSI
CASTSI
POP 0(D0)
PUSH 0(D0)
CASTSI
PUSH #3
CASTSI
CMPGTS
BRFS L1
PUSH #"A is greater than 3"
WRTLNS
BR L2
L1:
L2:
PUSH #"Done with if"
WRTLNS
MOV D0 SP
HLT

Tests/TestsFromPersons/tests/while_loop.mp
;Parse complete, stop poking me!
;Autogenerated Parse
;DO NOT EDIT
MOV SP D0
ADD SP #1 SP
PUSH #"PROGRAM: while_Loop"
WRTLNS
PUSH #"You should see jammin 5x, then hope jammin"
WRTLNS
PUSH #5
CASTSI
CASTSI
POP 0(D0)
L1:
PUSH 0(D0)
CASTSI
PUSH #0
CASTSI
CMPGTS
BRFS L2
PUSH #"We're jammin . . ."
WRTLNS
PUSH 0(D0)
CASTSI
PUSH #1
CASTSI
SUBS
CASTSI
POP 0(D0)
BR L1
L2:
PUSH #"And I hope you like jammin too."
WRTLNS
MOV D0 SP
HLT
