{
input : 4
input : 6
-333
2
10
-6
63700992
4
}


program NASTY;

var a: integer; b: integer; c: integer; d: integer; 
e: integer; f: integer; g: integer; h: integer; 
i: integer; j: integer; k: integer; l: integer; 
m: integer; n: integer; o: integer; p: integer;

begin

  read(g,h);

  a := -3+((((5*((((3-(6))))-0)))*21))-15;
  c := 6 div 3 div 2 div 1 + 1;

  e := 10 mod 11 mod 12 mod 13 mod 14 mod 15 mod 16;
  f := -(6);

  writeln(a);
  writeln(c);

  writeln(e);
  writeln(f);

  writeln(g*g*g*g*g*g*h*h*h*h*h*2, g);

end.
