{
input : 10
output:
1
2
3
}

program nasty;

{		var var var var var var var var var }
var	XOXOXOXOXOXOXOXOXOXOXOXOXOXO: integer;
 a, b: integer; c: integer; d: integer; 
	OXOXOXOXOXOXOXOXOXOXOXOXOXOX: integer;

{lsald;=-=-416469re85853.dfgag'dg';';g';g;ff;f'dd'd;;;d'dss'd;d;
=-2-era-0=-`09=2-`40`'h'fh';hk'dha
gaga'g;lfagk'ga
gadgaldbjladf0904042-3ihdf;h====\\\\\}

begin

  a := 55;
  b := 65;
  c := 10;

  if not(a < b) then
    writeln(9000000)
  else
    read(a);

  if a < b then
      writeln(1)
  else
      a := 20
  ;


  if (a = c) then
    if (b > c) then
      if (a > c) then
        begin
          writeln(100000);
        end
      else
        if (5+2) = (1+6) then
          begin
            writeln(2);
          end
        else
    else
  else
    begin
      writeln(100000);
    end
  ;


  if ((a > b) or (a > c)) or (a = c) then
    begin
      if not (a <> c) then
        begin
          if (b < a) or not (c <> c) then
            if (b = 55) then
              begin
                writeln(100000);
              end
            else
              writeln(3)
          else
            writeln(200000)
        end
    end
  else
    writeln(300000)
  ;


end.
